### PR TITLE
added adaptor method and one test

### PR DESCRIPTION
**Pull request by janisshin**
Added a method to emll/util.py for converting Antimony models into a form that is compatible with Cobra. 
Also added a test for this method which checks to see whether the stoichiometric matrices match after conversion

### CODE REVIEW

**Comment by janisshin** [comment]
I am not familiar with pytest, so I am not sure if I incorporated pytest correctly. 
However, the adaptor and the test should work. Please let me know if there are other things I can do to improve this pull request.

**Comment by mcnaughtonadm** [comment]
> I am not familiar with pytest, so I am not sure if I incorporated pytest correctly. However, the adaptor and the test should work. Please let me know if there are other things I can do to improve this pull request.

Taking a look, I'll test things and report back if something needs to be fixed.

**Comment by mcnaughtonadm** [comment]
Okay, so to finish out the pytest file, we will need to add an actual `.ant` model as a "tester". This will allow us to actually run the test and see if we get the expected outcome.

Then we can use some `pytest` functionality to point the test to the example model, this can be done with a `pytest.mark.paramaterize` decorator. Let's also change the name of the method from `compare__stoich_matrices(antimony_path)` to `test_antimony_to_cobra_conversion(antimony_path)`. `pytest` looks for the method to have the prefix `test_` or else it will interpret it as a helper function and not add it to the runtime. So making these changes will look something like:

```python
@pytest.mark.parametrize("antimony_path", [
    "path/to/your/antimony/model1.ant",
])

def test_antimony_to_cobra_conversion(antimony_path):
    ...
```

you can save the `model.ant` with the other example models under `emll/src/emll/test_models`.

Once you make these changes, you can run the script with `pytest test_antimony_utils.py`

**Comment by janisshin** [comment]
Hi Andrew, 
I made your suggested changes. 
I tried to test it in my terminal by running `pytest test_antimony_utils.py` in an environment with pytensor installed, but it gave me an error (image). However, if it works on your end, I imagine that this pull request should be good to close (hopefully!)


image

**Comment by mcnaughtonadm** [comment]
Perfect, let me check to see if it runs on my end. If it's something small not working, I can fix it so we don't need to go back and forth again. Then I can review and merge.

Thanks for this addition!

**Review by mcnaughtonadm — APPROVED** [review]
Made one more change to fix some small issues, but test passes now. Merging.

**Pull request merged**
